package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrders<M extends BaseOrders<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setUid(java.lang.Integer uid) {
		set("uid", uid);
		return (M)this;
	}

	public java.lang.Integer getUid() {
		return get("uid");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setCount(java.lang.Integer count) {
		set("count", count);
		return (M)this;
	}

	public java.lang.Integer getCount() {
		return get("count");
	}

	public M setOrderCode(java.lang.String orderCode) {
		set("order_code", orderCode);
		return (M)this;
	}

	public java.lang.String getOrderCode() {
		return get("order_code");
	}

	public M setOrderStatus(java.lang.Integer orderStatus) {
		set("order_status", orderStatus);
		return (M)this;
	}

	public java.lang.Integer getOrderStatus() {
		return get("order_status");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setIsDel(java.lang.Long isDel) {
		set("is_del", isDel);
		return (M)this;
	}

	public java.lang.Long getIsDel() {
		return get("is_del");
	}

}
