package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("consignee", "id", Consignee.class);
		arp.addMapping("orders", "id", Orders.class);
		arp.addMapping("token", "id", Token.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("verification_code", "id", VerificationCode.class);
	}
}

