package com.demo.common.model;

import com.demo.common.model.base.BaseConsignee;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Consignee extends BaseConsignee<Consignee> {
	public static final Consignee dao = new Consignee().dao();
}
