package com.demo.common.model;

import com.demo.common.model.base.BaseToken;
import com.demo.utils.DateUtil;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Token extends BaseToken<Token> {
	public static final Token dao = new Token().dao();

	public Token saveToken(Integer uid, String tokenStr) {
		Token token = new Token();
		token.setToken(tokenStr);
		token.setCreateTime(DateUtil.getNow());
		token.setUid(uid);
		token.setUpdateTime(DateUtil.getNow());
		Record record = new Record().setColumns(token);
		Db.save("token",record);
		return findToken(tokenStr);
	}

	public Token findToken(String tokenStr) {
		Token token = dao.findFirst("select * from token where token = ?",tokenStr);
		return token;
	}

	public void updateToken(String tokenStr) {
		Token token = dao.findFirst("select * from token where token = ?",tokenStr);
		if (token != null) {
			token.setUpdateTime(DateUtil.getNow());
			Record record = new Record().setColumns(token);
			Db.update("token",record);
		}
	}

}
