package com.demo.common.model;

import com.demo.common.model.base.BaseUser;
import com.demo.utils.DateUtil;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();

	public User saveUser(String mobile, String password) {
		User user = new User();
		user.setPassword(password)
				.setMobile(mobile)
				.setCreateTime(DateUtil.getNow());
		Record record = new Record().setColumns(user);
		boolean save = Db.save("user",record);
		if (save) {
			return findUser(mobile);
		} else {
			return null;
		}

	}

	public User findUser(String mobile) {
		return dao.findFirst("select * from user where mobile = "+mobile);
	}

	public User findUserByMobile(String mobile, String password) {
		User user = dao.findFirst("select * from user where mobile = ? and password = ?",mobile,password);
		return user;
	}

	public User findUserById(Integer uid) {
		User user = dao.findFirst("select * from user where id = ? ",uid);
		return user;
	}

}
